compiler/parser/DecafLexer.g: compiler/parser/DecafLexer.java
antlr4 compiler/parser/DecafLexer.g
javac compiler/parser/DecafLexer.java
javac compiler/parser/Main.java
java compiler/parser/Main compiler/parser/prueba.txt
